<a href="https://colab.research.google.com/github/williamokomba/An-electric-car-sharing-service-project/blob/master/Data_Cleaning_%26_EDA_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data cleaning & EDA**

In [ ]:
#importing the required libraries
import pandas as pd
import numpy as np

##**Maurine csv files**

In [ ]:
#1 file
per_county_df = pd.read_csv("/content/Cases_Per_County.csv")
per_county_df

                                            Unnamed: 0  ...  Nairobi
0                    Newcounty_cases 8th-November-2021  ...        0
1                    Newcounty_cases 7th-November-2021  ...        0
2                    Newcounty_cases 6th-November-2021  ...        0
3                    Newcounty_cases 5th-November-2021  ...        0
4                    Newcounty_cases 4th-November-2021  ...        0
..                                                 ...  ...      ...
505  Newcounty_cases Science/Covid-data-by-age/scan...  ...        0
506  Newcounty_cases Science/Covid-data-by-age/scan...  ...        0
507  Newcounty_cases Science/Covid-data-by-age/scan...  ...        0
508  Newcounty_cases Science/Covid-data-by-age/scan...  ...        0
509  Newcounty_cases Science/Covid-data-by-age/scan...  ...        0

[510 rows x 48 columns]

In [ ]:
per_county_df["Unnamed: 0"].unique()

array(['Newcounty_cases 8th-November-2021',
       'Newcounty_cases 7th-November-2021',
       'Newcounty_cases 6th-November-2021',
       'Newcounty_cases 5th-November-2021',
       'Newcounty_cases 4th-November-2021',
       'Newcounty_cases 3rd-November-2021',
       'Newcounty_cases 2nd-November-2021',
       'Newcounty_cases 1st-November-2021',
       'Newcounty_cases 31st-October-2021',
       'Newcounty_cases 30th-October-2021',
       'Newcounty_cases 29th-October-2021',
       'Newcounty_cases 28th-October-2021',
       'Newcounty_cases 27th-October-2021',
       'Newcounty_cases 26th-October-2021',
       'Newcounty_cases 25th-October-2021',
       'Newcounty_cases 24th-October-2021',
       'Newcounty_cases 23rd-October-2021',
       'Newcounty_cases 22nd-October-2021',
       'Newcounty_cases 21th-October-2021',
       'Newcounty_cases 20th-October-2021',
       'Newcounty_cases 19th-October-2021',
       'Newcounty_cases 18th-October-2021',
       'Newcounty_cases 17th-October-2021',
       'Newcounty_cases 16th-October-2021',
       'Newcounty_cases 15th-October-2021',
       'Newcounty_cases 14th-October-2021',
       'Newcounty_cases 13th-October-2021',
       'Newcounty_cases 12th-October-2021',
       'Newcounty_cases 10th-October-2021',
       'Newcounty_cases 9th-October-2021',
       'Newcounty_cases 8th-October-2021',
       'Newcounty_cases 7th-October-2021',
       'Newcounty_cases 6th-October-2021',
       'Newcounty_cases 5th-October-2021',
       'Newcounty_cases 4th-October-2021',
       'Newcounty_cases 3rd-October-2021',
       'Newcounty_cases 2nd-October-2021',
       'Newcounty_cases 1st-October-2021',
       'Newcounty_cases 30th-September-2021',
       'Newcounty_cases 29th-September-2021',
       'Newcounty_cases 28th-September-2021',
       'Newcounty_cases 27th-September-2021',
       'Newcounty_cases 26th-September-2021',
       'Newcounty_cases 25th-September-2021',
       'Newcounty_cases 24th-September-2021',
       'Newcounty_cases 23rd-September-2021',
       'Newcounty_cases 22nd-September-2021',
       'Newcounty_cases 21st-September-2021',
       'Newcounty_cases 20th-September-2021',
       'Newcounty_cases 19th-September-2021',
       'Newcounty_cases 18th-September-2021',
       'Newcounty_cases 17th-September-2021',
       'Newcounty_cases 16th-September-2021',
       'Newcounty_cases 15th-September-2021',
       'Newcounty_cases 14th-September-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/Press-Statement-on-Poland-Donation-September-13-2021',
       'Newcounty_cases 13th-September-2021',
       'Newcounty_cases 12th-September-2021',
       'Newcounty_cases 11th-September-2021',
       'Newcounty_cases 10th-September-2021',
       'Newcounty_cases 9th-September-2021',
       'Newcounty_cases 8th-September-2021',
       'Newcounty_cases 7th-September-2021',
       'Newcounty_cases 6th-September-2021',
       'Newcounty_cases 5th-September-2021',
       'Newcounty_cases 4th-September-2021',
       'Newcounty_cases 3rd-September-2021',
       'Newcounty_cases 2nd-September-2021',
       'Newcounty_cases 1st-September-2021',
       'Newcounty_cases 31st-August-2021',
       'Newcounty_cases 30th-August-2021',
       'Newcounty_cases 29th-August-2021',
       'Newcounty_cases 28th-August-2021',
       'Newcounty_cases 27th-August-2021',
       'Newcounty_cases 26th-August-2021',
       'Newcounty_cases 25th-August-2021',
       'Newcounty_cases 24th-August-2021',
       'Newcounty_cases 23rd-August-2021',
       'Newcounty_cases 22nd-August-2021',
       'Newcounty_cases 21th-August-2021',
       'Newcounty_cases 20th-August-2021',
       'Newcounty_cases 19th-August-2021',
       'Newcounty_cases 18th-August-2021',
       'Newcounty_cases 17th-August-2021',
       'Newcounty_cases 16th-August-2021',
       'Newcounty_cases 15th-August-2021',
       'Newcounty_cases 14th-August-2021',
       'Newcounty_cases 13th-August-2021',
       'Newcounty_cases 12th-August-2021',
       'Newcounty_cases 11th-August-2021',
       'Newcounty_cases 10th-August-2021',
       'Newcounty_cases 9th-August-2021',
       'Newcounty_cases 8th-August-2021',
       'Newcounty_cases 7th-August-2021',
       'Newcounty_cases 6th-August-2021',
       'Newcounty_cases 5th-August-2021',
       'Newcounty_cases 4th-August-2021',
       'Newcounty_cases 3rd-August-2021',
       'Newcounty_cases 2nd-August-2021',
       'Newcounty_cases 1st-August-2021',
       'Newcounty_cases 31st-July-2021',
       'Newcounty_cases 30th-July-2021-1',
       'Newcounty_cases 29th-July-2021', 'Newcounty_cases 28th-July-2021',
       'Newcounty_cases 27th-July-2021', 'Newcounty_cases 26th-July-2021',
       'Newcounty_cases 25th-July-2021', 'Newcounty_cases 24th-July-2021',
       'Newcounty_cases 23rd-July-2021', 'Newcounty_cases 22nd-July-2021',
       'Newcounty_cases 21st-July-2021', 'Newcounty_cases 20th-July-2021',
       'Newcounty_cases 19th-July-2021',
       'Newcounty_cases 18th-July-2021-1',
       'Newcounty_cases 17th-July-2021', 'Newcounty_cases 16th-July-2021',
       'Newcounty_cases 15th-July-2021-1',
       'Newcounty_cases 14th-July-2021-1',
       'Newcounty_cases 13th-July-2021',
       'Newcounty_cases 12th-July-2021-1',
       'Newcounty_cases 11th-July-2021-1',
       'Newcounty_cases 10th-July-2021-1',
       'Newcounty_cases 9th-July-2021', 'Newcounty_cases 8th-July-2021',
       'Newcounty_cases 7th-July-2021-1', 'Newcounty_cases 6th-July-2021',
       'Newcounty_cases 5th-July-2021', 'Newcounty_cases 4th-July-2021-1',
       'Newcounty_cases 3rd-July-2021-1',
       'Newcounty_cases 2nd-July-2021-1',
       'Newcounty_cases 1st-July-2021-1',
       'Newcounty_cases 30th-June-2021', 'Newcounty_cases 29th-June-2021',
       'Newcounty_cases 28th-June-2021', 'Newcounty_cases 27th-June-2021',
       'Newcounty_cases 26th-June-2021', 'Newcounty_cases 25th-June-2021',
       'Newcounty_cases 24th-June-2021', 'Newcounty_cases 23rd-June-2021',
       'Newcounty_cases 22nd-June-2021', 'Newcounty_cases 21st-June-2021',
       'Newcounty_cases 20th-June-2021', 'Newcounty_cases 19th-June-2021',
       'Newcounty_cases 18th-June-2021', 'Newcounty_cases 17th-June-2021',
       'Newcounty_cases 16th-June-2021', 'Newcounty_cases 15th-June-2021',
       'Newcounty_cases 14th-June-2021', 'Newcounty_cases 13th-June-2021',
       'Newcounty_cases 12th-June-2021', 'Newcounty_cases 11th-June-2021',
       'Newcounty_cases 10th-June-2021', 'Newcounty_cases 9th-June-2021',
       'Newcounty_cases 8th-June-2021', 'Newcounty_cases 7th-June-2021',
       'Newcounty_cases 6th-June-2021', 'Newcounty_cases 5th-June-2021',
       'Newcounty_cases 4th-June-2021', 'Newcounty_cases 3th-June-2021',
       'Newcounty_cases 2th-June-2021', 'Newcounty_cases 1st-June-2021',
       'Newcounty_cases 31st-May-2021', 'Newcounty_cases 29th-May-2021',
       'Newcounty_cases 27th-May-2021', 'Newcounty_cases 25th-May-2021',
       'Newcounty_cases 23rd-May-2021', 'Newcounty_cases 22nd-May-2021',
       'Newcounty_cases 21st-May-2021', 'Newcounty_cases 20th-May-2021-1',
       'Newcounty_cases 19th-May-2021', 'Newcounty_cases 18th-May-2021',
       'Newcounty_cases 17th-May-2021', 'Newcounty_cases 16th-May-2021',
       'Newcounty_cases 15th-May-2021', 'Newcounty_cases 14th-May-2021',
       'Newcounty_cases 13th-May-2021', 'Newcounty_cases 10th-May-2021',
       'Newcounty_cases 9th-May-2021', 'Newcounty_cases 8th-May-2021',
       'Newcounty_cases 7th-May-2021', 'Newcounty_cases 6th-May-2021',
       'Newcounty_cases 5th-May-2021', 'Newcounty_cases 4th-May-2021',
       'Newcounty_cases 3rd-May-2021', 'Newcounty_cases 2nd-May-2021',
       'Newcounty_cases 1st-May-2021', 'Newcounty_cases 30th-April-2021',
       'Newcounty_cases 29th-April-2021',
       'Newcounty_cases 28th-April-2021',
       'Newcounty_cases 27th-April-2021',
       'Newcounty_cases 26th-April-2021',
       'Newcounty_cases 25th-April-2021',
       'Newcounty_cases 24th-April-2021',
       'Newcounty_cases 23rd-April-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-22.4.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-20.4.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-19.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/April-18-COVID-19-Press-Statement1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-17.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-16.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-15.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-14.4.20212',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-13.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/1618237411229_NERC-MOH-Covid-19-brief-12.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-9.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/April-8-Covid-19-Press-Statement-I1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-RELEASE-7.4.20212',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-6th-April-20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-5.4.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-4.4.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-3.4.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-RESOLUTIONS-2.4.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/MARCH-31-2021-MOH-CS-COVID-RELEASE',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-30.3.20212021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-Covid-Release-29.3.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-Covid-Release-28.3.2021-i',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-Covid-Release-26.3.2021-i',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-25.3.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-23rd-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-22nd-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-19th-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/March-18-COVID-19-Press-Statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-17th-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-16th-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-15th-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-COVID-UPDATE-14.3.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/March-12COVID-19-Press-Statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-11th-March-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-brief-on-COVID-19-10th-March-20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERCC-Brief-on-COVID-19-8th-March-20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-COVID-UPDATE-7.3.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-COVID-UPDATE-6.3.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MoH-CS-COVID-19-UPDATE-5.3.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/C.S-Speech-and-March-4th-Covid-19-Update1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/March-3-COVID-19-Statement1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/March-2-COVID-19-Press-Statement1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/March-1-Covid-19-Press-Statement1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-28.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-27.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/Covid-19-Press-release-260221',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/Covid-19-Press-Statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-24.2.20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-23rd-February-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-22nd-February-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-21.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/February-20-Covid-19-Statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-19.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-18.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-10th-February-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/1612869503455_NERC-brief-on-COVID-19-9th-February-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-8.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/1612699040873_NERC-MOH-CS-COVID-UPDATE-7.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-6.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-Covid-19-update-on-5.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-4th-February-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-3rd-February-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-COVID-19-Update-2ND-FEB-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-Covid-19-update-1.2.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-31.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-30.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/JANUARY-29-COVID-19-STATEMENT',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-28th-January-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-27th-January-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-Covid-19-update-of-26.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-Covid-19-update-on-25.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-24.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-23.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-22.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-21st-January-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/January-20-Covid-19-Statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-19.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-18th-January-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-17.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/1610798111566_NERC-brief-on-COVID-19-16th-January-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-12th-January-2021-1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-8th-January-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-7th-Jan-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-6.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-5th-January-20211',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-4th-Dec-2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-3.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/January-2-Covid-19-Press-Statement-i',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/MOH-CS-REMARKS-ON-RTWF-WITH-KUCO-1.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-1.1.2021',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-31.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NATIONAL-EMERGENCY-RESPONSE-COMMITTEE-ON',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-28.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-MOH-CS-COVID-UPDATE-27.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-26.12.2020-E',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-25.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-23.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-Coronavirus-22nd-December-2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-21st-Dec-20201',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-20.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-19.12.20201',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/December-18-COVID-19-Statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/Day-276-statement',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-COVID-19-Update-16th-Dec-2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-15th-Dec-2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-14th-Dec-2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/1607867523886_December-13-Covid-19-Press-Statement-i',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-12.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-11.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-COVID-19-Update-10th-Dec-2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/Brief-No-260',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/DECEMBER-8-COVID-19-STATEMENT',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-Dec-7th-2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-CS-MOH-COVID-STATEMENT-06.12.2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/December-5-Covid-19-Press-Statement-i',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/Press-Statemnet-04_12_2020',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/UPDATE-ON-COVID-19-3RD-DECEMBER-1',
       'Newcounty_cases Science/Covid-data-by-age/scanned2pdf/NERC-brief-on-COVID-19-Dec-2nd-2020',

In [ ]:
#2 file
fatality_df = pd.read_csv("/content/fatalities.csv")
fatality_df.head()

  Age_group  ...  Fatalities 5th-August-2021
0       0-9  ...                         NaN
1     10-19  ...                         NaN
2     20-29  ...                         NaN
3     30-39  ...                         NaN
4     40-49  ...                         NaN

[5 rows x 91 columns]

In [ ]:
fatality_df.columns

Index(['Age_group', 'Fatalities 2nd-November-2021',
       'Fatalities 1st-November-2021', 'Fatalities 31st-October-2021',
       'Fatalities 30th-October-2021', 'Fatalities 29th-October-2021',
       'Fatalities 28th-October-2021', 'Fatalities 27th-October-2021',
       'Fatalities 26th-October-2021', 'Fatalities 25th-October-2021',
       'Fatalities 24th-October-2021', 'Fatalities 23rd-October-2021',
       'Fatalities 22nd-October-2021', 'Fatalities 21th-October-2021',
       'Fatalities 20th-October-2021', 'Fatalities 19th-October-2021',
       'Fatalities 18th-October-2021', 'Fatalities 17th-October-2021',
       'Fatalities 16th-October-2021', 'Fatalities 15th-October-2021',
       'Fatalities 14th-October-2021', 'Fatalities 13th-October-2021',
       'Fatalities 12th-October-2021', 'Fatalities 10th-October-2021',
       'Fatalities 9th-October-2021', 'Fatalities 8th-October-2021',
       'Fatalities 7th-October-2021', 'Fatalities 6th-October-2021',
       'Fatalities 5th-October-2021', 'Fatalities 4th-October-2021',
       'Fatalities 3rd-October-2021', 'Fatalities 2nd-October-2021',
       'Fatalities 1st-October-2021', 'Fatalities 30th-September-2021',
       'Fatalities 29th-September-2021', 'Fatalities 28th-September-2021',
       'Fatalities 27th-September-2021', 'Fatalities 26th-September-2021',
       'Fatalities 25th-September-2021', 'Fatalities 24th-September-2021',
       'Fatalities 23rd-September-2021', 'Fatalities 22nd-September-2021',
       'Fatalities 21st-September-2021', 'Fatalities 20th-September-2021',
       'Fatalities 19th-September-2021', 'Fatalities 18th-September-2021',
       'Fatalities 17th-September-2021', 'Fatalities 16th-September-2021',
       'Fatalities 15th-September-2021', 'Fatalities 14th-September-2021',
       'Fatalities  Science/data_pdfs/Press-Statement-on-Poland-Donation-September-13-2021',
       'Fatalities 13th-September-2021', 'Fatalities 12th-September-2021',
       'Fatalities 11th-September-2021', 'Fatalities 10th-September-2021',
       'Fatalities 9th-September-2021', 'Fatalities 8th-September-2021',
       'Fatalities 7th-September-2021', 'Fatalities 6th-September-2021',
       'Fatalities 5th-September-2021', 'Fatalities 4th-September-2021',
       'Fatalities 3rd-September-2021', 'Fatalities 2nd-September-2021',
       'Fatalities 1st-September-2021', 'Fatalities 31st-August-2021',
       'Fatalities 30th-August-2021', 'Fatalities 29th-August-2021',
       'Fatalities 28th-August-2021', 'Fatalities 27th-August-2021',
       'Fatalities 26th-August-2021', 'Fatalities 25th-August-2021',
       'Fatalities 24th-August-2021', 'Fatalities 23rd-August-2021',
       'Fatalities 22nd-August-2021', 'Fatalities 21th-August-2021',
       'Fatalities 20th-August-2021', 'Fatalities 19th-August-2021',
       'Fatalities 18th-August-2021', 'Fatalities 17th-August-2021',
       'Fatalities 16th-August-2021', 'Fatalities 15th-August-2021',
       'Fatalities 14th-August-2021', 'Fatalities 13th-August-2021',
       'Fatalities 12th-August-2021', 'Fatalities 11th-August-2021',
       'Fatalities 10th-August-2021', 'Fatalities 9th-August-2021',
       'Fatalities 8th-August-2021', 'Fatalities 7th-August-2021',
       'Fatalities 6th-August-2021', 'Fatalities 5th-August-2021'],
      dtype='object')

In [ ]:
#3 file
incomp_fal1= pd.read_csv(r"/content/Incomplete_Fatalities_by_Age - Incomplete_Fatalities_by_Age.csv")
incomp_fal1.head()

  Age_group  ...  Fatalities 23rd-June-2021
0       0-9  ...                          0
1     10-19  ...                          1
2     20-29  ...                          0
3     30-39  ...                          3
4     40-49  ...                          1

[5 rows x 511 columns]

In [ ]:
#3 file
incomp_fal2 = pd.read_csv("/content/Incomplete_Fatalities_by_Age.csv")
incomp_fal2.head()

  Age_group  ...  Fatalities 23rd-June-2021
0       0-9  ...                          0
1     10-19  ...                          1
2     20-29  ...                          0
3     30-39  ...                          3
4     40-49  ...                          1

[5 rows x 511 columns]

In [ ]:
#4 file
incomp_newcas1= pd.read_csv("/content/Incomplete_New_Cases_By_Age - Incomplete_New_Cases_By_Age.csv")
incomp_newcas1.head()

  Age_group  ...  New_cases 23rd-June-2021
0       0-9  ...                        16
1     10-19  ...                        27
2     20-29  ...                        89
3     30-39  ...                       136
4     40-49  ...                       103

[5 rows x 511 columns]

In [ ]:
#5 file
incomp_newcas2= pd.read_csv("/content/Incomplete_New_Cases_By_Age.csv")
incomp_newcas2.head()

  Age_group  ...  New_cases 23rd-June-2021
0       0-9  ...                        16
1     10-19  ...                        27
2     20-29  ...                        89
3     30-39  ...                       136
4     40-49  ...                       103

[5 rows x 511 columns]

In [ ]:
#6 file
cases_age = pd.read_csv("/content/cases_by_age.csv")
cases_age.head()

  Age_group  ...  New_cases 5th-August-2021
0       0-9  ...                        NaN
1     10-19  ...                        NaN
2     20-29  ...                        NaN
3     30-39  ...                        NaN
4     40-49  ...                        NaN

[5 rows x 91 columns]

##**Emmanuel datasets**

In [ ]:
clean_df = pd.read_csv("/content/clean_pdf.csv")
clean_df.head()

       Unnamed: 0  20 march 2020  ...  12 march 2020  july 18 2020
0         Baringo              0  ...              0             0
1           Bomet              0  ...              0             0
2         Bungoma              0  ...              0             1
3           Busia              0  ...              0            15
4  ElgeyoMarakwet              0  ...              0             0

[5 rows x 179 columns]

In [ ]:
data2 = pd.read_csv("/content/clean_pdf_log_file.csv")
data2

     Unnamed: 0  ...                  1
0             0  ...      20 march 2020
1             1  ...       1 april 2020
2             2  ...       july 16 2020
3             3  ...   december 13 2020
4             4  ...       april 8 2021
..          ...  ...                ...
173         173  ...   september 9 2021
174         174  ...  september 13 2021
175         175  ...       july 19 2020
176         176  ...      12 march 2020
177         177  ...       july 18 2020

[178 rows x 3 columns]

## **Scanned files**

In [ ]:
#1. loading scanned dataset
scanned_df = pd.read_csv("/content/scanned_pdf.csv")
#
#previewing the top 5 rows;
scanned_df.head()

       Unnamed: 0  september 11 2020  ...  december 3 2020  september 18 2020
0         Baringo                  0  ...                0                  1
1           Bomet                  2  ...               11                  0
2         Bungoma                  1  ...               19                  0
3           Busia                  2  ...                7                  0
4  ElgeyoMarakwet                  0  ...                0                  1

[5 rows x 326 columns]

In [ ]:
#checking the last 5 rows
scanned_df.tail()

    Unnamed: 0  september 11 2020  ...  december 3 2020  september 18 2020
42     Turkana                  0  ...                2                  0
43  UasinGishu                 13  ...               14                  6
44      Vihiga                  0  ...                0                  0
45       Wajir                  0  ...                0                  0
46   WestPokot                  0  ...                0                  0

[5 rows x 326 columns]

In [ ]:
#checking the shape

records1=scanned_df.shape[1]
variables1 = scanned_df.shape[0]
#
print(r"The dataset contains {} records and {} variables".format(records1, variables1))

The dataset contains 326 records and 47 variables

In [ ]:
#checking dataset information
scanned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Columns: 326 entries, Unnamed: 0 to september 18 2020
dtypes: int64(325), object(1)
memory usage: 119.8+ KB

In [ ]:
# 2. loading the scanned dataset description
scanned_des_df =pd.read_csv("/content/scanned_pdf_log_file.csv")
#
#previewing the top 5 rows
scanned_des_df[:10]

   Unnamed: 0  ...                  1
0           0  ...  september 11 2020
1           1  ...    january 16 2021
2           2  ...    february 7 2021
3           3  ...    february 9 2021
4           4  ...      april 12 2021
5           5  ...  september 16 2020
6           6  ...      april 18 2021
7           7  ...     18 august 2020
8           8  ...          june 2020
9           9  ...    december 9 2020

[10 rows x 3 columns]

In [ ]:
#Making a copy for data cleaning so that we don't intefere with the original dataset.
scanned_df1 = scanned_df.copy(deep=True)

In [ ]:
scanned_df1.rename(columns={"Unnamed: 0": "County", "june 2020":"1 june 2020", "no date":"14 april 2020",
"april 2020 NO1": "18 april 2020", "april 2020 NO2": "20 april 2020", "april 2020 NO3":"21 april 2020",
"april 2020 NO4": "22 april 2020", "april 2020 NO5":"23 april 2020", "april 2020 NO6":"24 april 2020",
"april 2020 NO7": "26 april 2020", "april 2020 NO8":"29 april 2020", "april 2020 NO9": "30 april 2020",
"may 2020": "2 may 2020","may 2020 NO10":"7 may 2020","may 2020 NO11":"9 may 2020",
"may 2020 NO12": "11 may 2020", "may 2020 NO13": "12 may 2020", "may 2020 NO14": "15 may 2020",
"may 2020 NO15": "20 april 2020", "may 2020 NO16": "27 may 2020", "may 2020 NO17": "29 april 2020",
"may 2020 NO18":"30 may 2020", "no date NO19": "31 may 2020", "june 2020 NO20": "2 june 2020",
"june 2020 NO21": "9 june 2020", "june 2020 NO22":"11 june 2020", "april 2020 NO23":"9 april 2020",
"march 2020": "4 march 2020", "july":"1 july 2020", "july NO24":"10 july 2020", "july 2020 NO25":"4 july 2020"

}, inplace=True)

#preview
scanned_df1.head()

           County  september 11 2020  ...  december 3 2020  september 18 2020
0         Baringo                  0  ...                0                  1
1           Bomet                  2  ...               11                  0
2         Bungoma                  1  ...               19                  0
3           Busia                  2  ...                7                  0
4  ElgeyoMarakwet                  0  ...                0                  1

[5 rows x 326 columns]

In [ ]:
scanned_df1.columns[:11]

Index(['Unnamed: 0', 'september 11 2020', 'january 16 2021', 'february 7 2021',
       'february 9 2021', 'april 12 2021', 'september 16 2020',
       'april 18 2021', '18 august 2020', 'june 2020', 'december 9 2020'],
      dtype='object')

In [ ]:
scanned_df1.columns[0:11]

Index(['Unnamed: 0', 'september 11 2020', 'january 16 2021', 'february 7 2021',
       'february 9 2021', 'april 12 2021', 'september 16 2020',
       'april 18 2021', '18 august 2020', 'june 2020', 'december 9 2020'],
      dtype='object')